[project]
name = "image-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pytz>=2025.1",
    "requests>=2.32.3",
    "schedule>=1.2.2",
]
